name: Build Day Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build for ${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - arch: x86_64
            runner: ubuntu-latest
          - arch: aarch64
            runner: ubuntu-24.04-arm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU for aarch64 (if needed)
        if: matrix.arch == 'aarch64' && matrix.runner == 'ubuntu-latest'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: aarch64

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          architecture: ${{ matrix.arch == 'x86_64' && 'x64' || 'arm64' }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller requests beautifulsoup4 termcolor

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --name day-${{ matrix.arch }} day.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: day-${{ matrix.arch }}
          path: dist/day-${{ matrix.arch }}
