name: Build Day Executable

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    name: Build for ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, aarch64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU for aarch64
        if: matrix.arch == 'aarch64'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: aarch64

      - name: Build executable
        uses: uraimo/run-on-arch-action@v3
        with:
          arch: ${{ matrix.arch }}
          distro: fedora_latest
          githubToken: ${{ github.token }}
          install: |
            dnf install -y python3 python3-pip python3-devel dnf5
            pip install pyinstaller requests beautifulsoup4 termcolor
          run: |
            pyinstaller --onefile --name day-${{ matrix.arch }} day.py
            mv dist/day-${{ matrix.arch }} /artifacts/
          dockerRunArgs: |
            --volume "${PWD}/dist:/artifacts"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: day-${{ matrix.arch }}
          path: dist/day-${{ matrix.arch }}
